### PR TITLE
docs: Recommend title case not sentence case for list-of-links labels

### PR DESCRIPTION
**Pull request by apetro**
In prototyping recent list-of-links usage with UX consultant @mrdahman , title case rather than sentence case seemed to be preferable for the within-`list-of-links`-type-widget link labels.

star-widget-prototype

This is at odds with the style recommendation currently embedded in the widget documentation (though interestingly the example screenshot in the documentation is already using title case rather than sentence case for this labelling). This changeset would update the guidance to match what we seem to now be preferring.

Personally, I'd have gone with sentence case. But this isn't about me personally. :) So this PR is about reconciling what professionally we ought to be recommending.

----

Contributor License Agreement adherence:

- [x] This Contribution is under the terms of Individual [Contributor License Agreements][] (and also Corporate Contributor License Agreements to the extent applicable) appearing in the [Apereo CLA roster][].

[Apereo CLA roster]: http://licensing.apereo.org/completed-clas
[Contributor License Agreements]: https://www.apereo.org/licensing/agreements

### CODE REVIEW

**Comment by mrdahman** [comment]
I think a call to action looks better as title case. Sentence case without punctuation at the end is a little annoying to me personally, but more than that, I think it just looks more impressive. I admit I'm also biased by German immersion, which capitalizes liberally. :)

**Comment by prtreige** [comment]
I don't want to throw a wrench in @mrdahman reco's but I'm still an advocate for sentence case, per Material Guidelines, and though it's hardly settled in terms of usability research, sentence case has strong advantages for read-ability. See https://medium.com/@jsaito/making-a-case-for-letter-case-19d09f653c98.

**Comment by apetro** [comment]
I think this is the right soul-searching to be prompting, albeit over an elongated time period so that @mrdahman can enjoy her justly earned leave this week and re-engage next week or so. :)

Stipulating that our current realization of Material Design is imperfect and as much aspirational as it is achieved, this is another one of those opportunities to decide: are we literally adopting Material Design, as best we can, and of course layering on local considerations and working within its extensibility for typography and branding? Or are we working towards our own design system somewhat inspired by Material Design? I see efficiencies, leverage to be gained in the former.

**Comment by mrdahman** [comment]
That's a great point @prtreige . Readability is a concern with title case, though somehow in the specific example of the widget we were looking at, the two documents that we put in title case were easier to understand in title case than sentence case. Perhaps in that instance it was more of an example of a proper noun, i.e., a named document. (Also, as an aside, the character limit on the list of links widgets doesn't allow us to write anything that would be too difficult to read in title case.) But yes, I agree that we run into the larger problem of how closely we are adhering to Material Design. And, @apetro , I fully acknowledge that there are efficiencies with literally adopting Material Design, but think there might also be some wiggle room if something feels easier to understand. Thoughts?

**Comment by apetro** [comment]
Hard cases make bad law.

I think the most important error here was my prematurely trying to generalize a change to the design system from one goofy `list-of-links` widget making exceptions to the design system. Too soon.

Let's 

+ revert this specific changeset and drop the `search-with-links` parallel in #597 ,
+  keep the guidance we had (sentence case) (think of it as a nod to *stare decisis*)
+ accept the MyUW-local one-off ad-hoc title case usage in the one specific goofy widget because it's literally what we've been asked to do locally, temporarily accepting a little local MyUW weirdness to shield the open source product from turbulence
+ work more generally to really grapple with what our relationship to Material Design is and ought to be
+ revisit this when it comes up again. I imagine it will.

**Pull request merged**
